### ISSUE TITLE
WARNING AppDaemon: Unable to find class Notifreeze in module notifreeze - 'notifreeze' is not initialized

### ISSUE THREAD

**Issue by jokerigno** [benleb/ad-notifreeze#2]
Hi, it's me again.

I wanted to test your app now but when I tried I see these errors in log:

_WARNING AppDaemon: Unable to find class Notifreeze in module notifreeze - 'notifreeze' is not initialized
WARNING AppDaemon: Unable to find module notifreeze - initialize() skipped_

This is my config in apps.yaml

```
notifreeze:
  module: notifreeze
  class: Notifreeze
  notify_service: notify.xxxxxxxxxxxxxx
  outdoor_temperature: sensor.daikinapxxxxx_outside_temperature
```

**Comment by benleb** [comment]
ah sorry, its a documentation error... the class name has a big 'F'. Try this:

```yaml
notifreeze:
  module: notifreeze
  class: NotiFreeze
  notify_service: notify.xxxxxxxxxxxxxx
  outdoor_temperature: sensor.daikinapxxxxx_outside_temperature
```
