### ISSUE TITLE
Support for also manualy add sensors not by name

### ISSUE THREAD

**Issue by accessone67** [benleb/ad-notifreeze#3]
Can you add also that sensors can be added manualy not by the name. In my config I have sensors named like "door_window_sensor_158d0002c908bc" .. and I cant use this plugin because of that..

**Comment by jokerigno** [comment]
I have this issue too. @benleb you said that can be configured manually but how ? There's no trace in docs.

Moreover how the message is written ? In english I suppose. But how can we localize it?

TY

**Comment by benleb** [comment]
@accessone67 & @jokerigno if anyone of you wants to test the master? 🤪 And sure, you can configure your sensors directly or, maybe more convenient, use an alias for auto-discovery 🥳 Please read the readme about the new idea/concept and configuration! The example config is my currently running one, should work 👍

**Comment by benleb** [comment]
okay, v0.5.0 released with the requested feature :) closing here now as this issue is resolved. (if not. let me know ;))

**Comment by jokerigno** [comment]
OK I'll make some tests. In case I'm available to localize in Italian (just need to know which phrases I should translate)

**Comment by jokerigno** [comment]
Here I am.

I put this config 

```
notifreeze:
  module: notifreeze
  class: NotiFreeze
  notify_service: notify.telegrammarco
  always_notify: true
  outdoor: sensor.daikinap73415_outside_temperature
  max_difference: 4.2
  delays:
    initial: 3
    reminder: 7
  rooms:
    - name: Cucina
      door_window: 
        - binary_sensor.portafinestracucina
        - binary_sensor.finestra_cucina
      indoor:
        - sensor.temperatura_cucina
    - name: Soggiorno
      door_window: 
        - binary_sensor.portafinestrasoggiorno
      indoor:
        - sensor.temperatura_soggiorno
    - name: Studio
      door_window: 
        - binary_sensor.001558a99d4529_state
      indoor:
        - sensor.temperatura_studio
    - name: Camera da Letto
      door_window: 
        - binary_sensor.001558a99d4a8d_state
      indoor:
        - sensor.temperatura_camera_da_letto
    - name: Camera di Adele
      door_window: 
        - binary_sensor.portafinestracameradiadele
        - binary_sensor.001558a99ef4be_state
      indoor:
        - sensor.temperatura_camera_di_adele
```

and then opened all the windows. Nothing appened (even if the temperature went down from 22 to 16 in a room with an external temp of 17 degrees.

**Comment by accessone67** [comment]
Hei

Same here.

My config is:
`notifreeze:
  module: notifreeze
  class: NotiFreeze
  notify_service: notify.me_telegram
  outdoor: sensor.weather_temperature
  max_difference: 5
  delays:
    initial: 1
    reminder: 2
  rooms:
    - name: Livingroom
      door_window: binary_sensor.door_window_sensor_158d000292546f 
      indoor: sensor.temperature_158d000208f610   
    - name: Bedroom
      door_window: 
        - binary_sensor.door_window_sensor_158d0002c908bc
        - binary_sensor.door_window_sensor_158d0002c133e1
      indoor: sensor.temperature_158d0001e81b0d `

If I look in appdaemon log I see
`2020-10-13 11:06:59.890406 INFO notifreeze: ❄️  Livingroom Living room window opened, -13.4°C → reminder in 1min`

But the notification will never arrive. It just like stop the job.
I think we are almost there need to fix this small bug.

**Comment by benleb** [comment]
sorry, seems like a c&p bug 🤦  can you confirm it's working in the master now? if so, I will release a new version :)

**Comment by jokerigno** [comment]
chenged to master on HACS. I'll do some test and let you know :)

**Comment by benleb** [comment]
Thanks! That's how it should look (with debug output enabled (and also AutoMoLi to manage the lights))
![image](https://user-images.githubusercontent.com/512997/95856043-b41d4680-0d59-11eb-8260-ebed12c19c63.png)

**Comment by benleb** [comment]
fixed in [v0.5.1](https://github.com/benleb/ad-notifreeze/releases/tag/v0.5.1), thanks!

**Comment by jokerigno** [comment]
Sorry @benleb  but I still miss something.

I added this config:

```
notifreeze:
  module: notifreeze
  class: NotiFreeze
  notify_service: notify.telegrammarco
  outdoor: sensor.dark_sky_apparent_temperature #sensor.daikinap73415_outside_temperature
  max_difference: 4
  delays:
    initial: 1
    reminder: 2
  rooms:
  - name: Soggiorno
    door_window: binary_sensor.portafinestrasoggiorno
    indoor: sensor.temperatura_soggiorno
  - name: Cucina
    door_window:
    - binary_sensor.portafinestracucina
    - binary_sensor.finestra_cucina
    indoor: sensor.temperatura_cucina
  - name: Studio
    door_window: binary_sensor.001558a99d4529_state
    indoor: sensor.temperatura_studio
  - name: Camera da Letto
    door_window: binary_sensor.001558a99d4a8d_state
    indoor: sensor.temperatura_camera_da_letto
  - name: Camera di Adele
    door_window:
    - binary_sensor.portafinestracameradiadele
    - binary_sensor.001558a99ef4be_state
    indoor: sensor.temperatura_camera_di_adele
  - name: Bagno Principale
    door_window: binary_sensor.001558a99d4e50_state
    indoor: sensor.temperatura_bagno_principale
  - name: Bagno Secondario
    door_window: binary_sensor.001558a99ef07a_state
    indoor: sensor.temperatura_bagno_secondario
```
And I see it's loading. But then nothing happens. I opened the window and the inside room was 22 while ext 13 and I waited for a notification that didn't arrived.

Any suggestion?
